name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your main branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install  # or yarn install

      - name: Build Project
        run: yarn build  # Adjust this based on your build process

      - name: Prepare Deploy Directory
        run: |
          mkdir -p deploy/dist
          cp index.html deploy/
          cp -R public deploy/
          cp dist/bundle.js deploy/dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Target branch
          folder: deploy
